fix(charts) add quote around daemon_environment value
This change need to to avoid validation error when run helm install.
Type of spec.template.spec.containers[].env[].value field must be
string.

how to test this change (it also reproduce problem)

```
$ cat<<EOS > values.yaml
daemon_environment:
  SEND_LOGS_TO_NSQ: "true"
EOS

$ helm install --namespace deis-fluentd ./charts/fluentd -f values.yaml
```

Before this change, we got following error.

> Error: error validating "": error validating data: expected type string,
for field spec.template.spec.containers[0].env[0].value, got bool